// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package macogql

import (
	"github.com/loivis/marvel-comics-api-data-loader/maco"
)

type CharactersResult struct {
	Characters []*maco.Character `json:"characters"`
	PageInfo   *PageInfo         `json:"pageInfo"`
	TotalCount int               `json:"totalCount"`
}

type ComicsResult struct {
	Comics     []*maco.Comic `json:"comics"`
	PageInfo   *PageInfo     `json:"pageInfo"`
	TotalCount int           `json:"totalCount"`
}

type CreatorsResult struct {
	Creators   []*maco.Creator `json:"creators"`
	PageInfo   *PageInfo       `json:"pageInfo"`
	TotalCount int             `json:"totalCount"`
}

type EventsResult struct {
	Events     []*maco.Event `json:"events"`
	PageInfo   *PageInfo     `json:"pageInfo"`
	TotalCount int           `json:"totalCount"`
}

type PageInfo struct {
	End     int  `json:"end"`
	HasNext bool `json:"hasNext"`
}

type SeriesResult struct {
	Series     []*maco.Series `json:"series"`
	PageInfo   *PageInfo      `json:"pageInfo"`
	TotalCount int            `json:"totalCount"`
}

type StoriesResult struct {
	Stories    []*maco.Story `json:"stories"`
	PageInfo   *PageInfo     `json:"pageInfo"`
	TotalCount int           `json:"totalCount"`
}
