// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package macogql

import (
	"github.com/loivis/marvel-comics-api-data-loader/maco"
)

type CharactersResult struct {
	Items      []*maco.Character `json:"items"`
	PageInfo   *PageInfo         `json:"pageInfo"`
	TotalCount int               `json:"totalCount"`
}

type ComicsResult struct {
	Items      []*maco.Comic `json:"items"`
	PageInfo   *PageInfo     `json:"pageInfo"`
	TotalCount int           `json:"totalCount"`
}

type CreatorsResult struct {
	Items      []*maco.Creator `json:"items"`
	PageInfo   *PageInfo       `json:"pageInfo"`
	TotalCount int             `json:"totalCount"`
}

type EventsResult struct {
	Items      []*maco.Event `json:"items"`
	PageInfo   *PageInfo     `json:"pageInfo"`
	TotalCount int           `json:"totalCount"`
}

type PageInfo struct {
	End     int  `json:"end"`
	HasNext bool `json:"hasNext"`
}

type SeriesResult struct {
	Items      []*maco.Series `json:"items"`
	PageInfo   *PageInfo      `json:"pageInfo"`
	TotalCount int            `json:"totalCount"`
}

type StoriesResult struct {
	Items      []*maco.Story `json:"items"`
	PageInfo   *PageInfo     `json:"pageInfo"`
	TotalCount int           `json:"totalCount"`
}
